name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
    
      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist
          color_snake: "#ffffff"  # Cor da cobrinha
          color_dots: "#000000, #222222, #333333"  # Cores dos pontos
          color_background: "#000000"  # Cor de fundo preta

      - name: Show build status
        run: git status

      - name: Push the content to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

